# Generated by Django 6.0.1 on 2026-01-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('passwordhash', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=35)),
                ('lname', models.CharField(max_length=35)),
                ('userrole', models.CharField(choices=[(1, 'geologist'), (2, 'logger')], default=1)),
            ],
        ),
    ]
