# Generated by Django 6.0.1 on 2026-02-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='passwordhash',
            field=models.CharField(max_length=128),
        ),
    ]
