# Generated by Django 6.0.1 on 2026-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_passwordhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='signedUp',
            field=models.BooleanField(default=False),
        ),
    ]
