# Generated by Django 6.0.1 on 2026-02-28 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_signedup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillProgram',
            fields=[
                ('programid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('orebody', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('totalholes', models.IntegerField(default=0)),
                ('totalmeters', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('dateplanned', models.DateField(auto_now_add=True)),
                ('dateupdated', models.DateField(auto_now=True)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
            ],
        ),
    ]
