# Generated by Django 6.0.1 on 2026-03-03 10:36


from django.utils import timezone
from django.db import migrations
from django.contrib.auth import get_user_model

def create_api_user(apps, schema_editor):
    user = get_user_model()
    username = 'api-service-user'

    if not user.objects.filter(username=username).exists():
        user = user.objects.create_user(
            username=username,
            email='drilltekclient@drilltek.com',
            password='changetodotenv',
            is_active = True,
            last_login=timezone.now() # Missing for containerisation. 
        )
        print(f"Created service user: {user.id}")


def remove_api_user(apps, schema_editor):
    user=get_user_model()
    user.objects.filter(username='api-service-user').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_drillprogram'),
    ]

    operations = [
        migrations.RunPython(create_api_user,remove_api_user),
    ]
