# Generated by Django 6.0.1 on 2026-03-06 21:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_api_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drillhole',
            fields=[
                ('holeid', models.AutoField(primary_key=True, serialize=False)),
                ('xcoord', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ycoord', models.DecimalField(decimal_places=2, max_digits=8)),
                ('zcoord', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dip', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('azimuth', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(360.0)])),
                ('length', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100000.0)])),
                ('type', models.CharField(choices=[(1, 'Exploration'), (2, 'Infill')], default=2)),
                ('dateplanned', models.DateField(auto_now_add=True)),
                ('dateupdated', models.DateField(auto_now=True)),
                ('programid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drillprogram')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
            ],
        ),
    ]
