# Generated by Django 6.0.1 on 2026-03-10 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_drillhole'),
    ]

    operations = [
        migrations.CreateModel(
            name='LithLog',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000.0)])),
                ('end', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000.0)])),
                ('lithcode', models.CharField(choices=[('W_Bm', 'waulsortian biomicrite'), ('W_Dol', 'Dolomitised Reef'), ('W_WL', 'Wavy Laminated Facies'), ('W_LTU', 'Lower Transition Unit'), ('W_Lll', 'Lower Limestone Lens'), ('ABL_Nm', 'Nodular Micrite Unit'), ('ABL_En', 'ABL Encrinite'), ('ABL', 'Undifferentiated ABL'), ('ABL_Uppr', 'Upper ABL'), ('ABL_Lwr', 'ABL Lower'), ('OOL', 'Lisduff oolite undiff'), ('OOL_Uppr', 'Upper Lisduff Ool'), ('OOL_Mid', 'Middle Lisduff Ool'), ('OOL_Lwr', 'Lower Lisduff Ool'), ('SLT', 'Undifferentiated Siltite'), ('MU', 'Undifferenciated Micrite'), ('ARG', 'Undifferenciated Argillite'), ('GSTN', 'Undifferenciated Grainstone'), ('DOL', 'Undifferenciated Dolomite'), ('BDOL', 'Undifferenciated Black Dolomite'), ('LST', 'Undifferenciated Limestone')])),
                ('comment', models.CharField(max_length=500)),
                ('lithology', models.CharField(max_length=35)),
                ('dateLogged', models.DateField(auto_now_add=True)),
                ('holeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drillhole')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
            ],
        ),
    ]
