# Generated by Django 6.0.1 on 2026-03-10 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lithlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lithlog',
            name='end',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100000.0)]),
        ),
        migrations.AlterField(
            model_name='lithlog',
            name='start',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100000.0)]),
        ),
    ]
