# Generated by Django 6.0.1 on 2026-03-12 19:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_lithlog_end_alter_lithlog_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlterationLog',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100000.0)])),
                ('end', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100000.0)])),
                ('alterationcode', models.CharField(choices=[('BMB_I', 'Incipient Black Matrix Breccia'), ('BMB_W', 'Weak Black Matrix Breccia'), ('BMB', 'Black Matrix Breccia'), ('BMB_S', 'Strong Black Matrix Breccia'), ('WMB_I', 'Incipient White Matrix Breccia'), ('WMB_W', 'Weak White Matrix Breccia'), ('WMB', 'White Matrix Breccia'), ('WMB_S', 'Strong White Matrix Breccia'), ('FE_Ox', 'Fe Oxides'), ('MN_OX', 'Mn Oxides'), ('LE_W', 'Weak Leaching'), ('LE', 'Leaching'), ('LE_S', 'Strong Leaching'), ('WTD_W', 'Weak Weathering'), ('WTD', 'Weathering'), ('WTD_S', 'Strong Weathering'), ('BHY_Dol', 'Black Hydrothermal Dolomite'), ('WHY_Dol', 'White Hydrothermal Dolomite')])),
                ('comment', models.CharField(max_length=500)),
                ('alterationtype', models.CharField(max_length=35)),
                ('dateLogged', models.DateField(auto_now_add=True)),
                ('holeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drillhole')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
            ],
        ),
    ]
