# Generated by Django 6.0.1 on 2026-03-12 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alterationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureLog',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100000.0)])),
                ('end', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100000.0)])),
                ('structurecode', models.CharField(choices=[('F1', 'Weak Fault'), ('F2', 'Moderate Fault'), ('F3', 'Strong Fault'), ('F4', 'Strongest Fault'), ('FLT', 'Fault Zone'), ('GOU', 'Fault Gouge'), ('HY_BX', 'Hydrothermal Breccia'), ('BX', 'Non Hydrothermal Breccia'), ('VCAL', 'Calcite Vein'), ('VDOL', 'Dolomite Vein'), ('VPDOL', 'Pink Plug dolomite vein'), ('VQTZ', 'Quartz Vein'), ('VHAEM', 'Haematite Vein'), ('J1', 'Weak Joint'), ('J2', 'Moderate Joint'), ('J3', 'Strong Joint'), ('J4', 'Strongest Joint'), ('S1', 'Weak Slip Plane'), ('S2', 'Moderate Slip Plane'), ('S3', 'Strong Slip Plane'), ('S4', 'Strongest Slip Plane'), ('FLD', 'Fold'), ('B', 'Bedding')])),
                ('comment', models.CharField(max_length=500)),
                ('structuretype', models.CharField(max_length=35)),
                ('dip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(90)])),
                ('dateLogged', models.DateField(auto_now_add=True)),
                ('holeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drillhole')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
            ],
        ),
    ]
