# Generated by Django 6.0.1 on 2026-03-12 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_structurelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralLog',
            fields=[
                ('sampleid', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100000.0)])),
                ('end', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100000.0)])),
                ('estimate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('zn', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('pb', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fe', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ag', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999000.0)])),
                ('comment', models.CharField(max_length=500)),
                ('sampletype', models.CharField(choices=[('BLANK', 'Blank'), ('STD1', 'Standard One'), ('STD2', 'Standard Two'), ('STD3', 'Standard Three'), ('SAMPLE', 'Core Sample')])),
                ('texture', models.CharField(choices=[('D', 'Disseminated'), ('R', 'Replacement'), ('M', 'Massive'), ('Sm', 'Semi-massive'), ('X', 'Breccia'), ('F', 'Fracture Filling'), ('Rm', 'Remobilised'), ('S', 'Stringer'), ('V', 'Veins')])),
                ('dateLogged', models.DateField(auto_now_add=True)),
                ('holeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drillhole')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.users')),
            ],
        ),
    ]
