# Generated by Django 6.0.1 on 2026-03-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_minerallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='minerallog',
            name='assaysUploaded',
            field=models.BooleanField(default=False),
        ),
    ]
