# Generated by Django 6.0.1 on 2026-03-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_minerallog_assaysuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minerallog',
            name='texture',
            field=models.CharField(choices=[('D', 'Disseminated'), ('R', 'Replacement'), ('M', 'Massive'), ('Sm', 'Semi-massive'), ('X', 'Breccia'), ('F', 'Fracture Filling'), ('Rm', 'Remobilised'), ('S', 'Stringer'), ('V', 'Veins'), ('T', 'Trace'), ('B', 'Barren')]),
        ),
    ]
