# Generated by Django 6.0.1 on 2026-03-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_minerallog_texture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minerallog',
            name='sampleid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
