# Generated by Django 6.0.1 on 2026-03-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_minerallog_sampleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alterationlog',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lithlog',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='minerallog',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='structurelog',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
