# Generated by Django 6.0.1 on 2026-03-24 22:30
# Ignore, failed migration as password is unhashed and login does hash, fails every time
from django.db import migrations


def add_first_user(apps, schema_editor):

    Users = apps.get_model('api', 'Users')

   
    user, created = Users.objects.get_or_create(
        email='j.sykes@drilltek.com', 
        defaults={
            
            'passwordhash': 'secretsecretsecret',  
            'fname': 'John',
            'lname': 'Sykes',
            'userrole': 1,
            'signedUp': False,
        }
    )

    if created:
        print("Added default user")
    else:
        print("Default user already exists")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_alterationlog_comment_alter_lithlog_comment_and_more'),
    ]

    operations = [
        migrations.RunPython(add_first_user),
    ]
