# Generated by Django 6.0.1 on 2026-03-24 23:11
# Creates dummy user for checking app
from django.db import migrations



def add_second_user(apps, schema_editor):
    Users = apps.get_model('api', 'Users')

    user, created = Users.objects.get_or_create(
        email='j.owen@drilltek.com',  
        defaults={
            
            'passwordhash': 'secretsecretsecret',
            'fname': 'John',
            'lname': 'Owen',
            'userrole': 1,
            'signedUp': False,
        }
    )

    if created:
        print("Added default user")
    else:
        print("Default user already exists")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20260324_2230'),
    ]

    operations = [
        migrations.RunPython(add_second_user),
    ]
